### ISSUE TITLE
GDPR - Cookies

### ISSUE THREAD

**Issue by BenWortley** [Barbapapazes/nuxt-clarity-analytics#20]
Would adding an easy way to manage consent using this module be possible?

https://learn.microsoft.com/en-us/clarity/setup-and-installation/cookie-consent

**Comment by Barbapapazes** [comment]
Hey 👋,

Yes, I can update this module and try to simplify this!

**Comment by Barbapapazes** [comment]
I will update the package and I think I will also update the package to recommend trying https://scripts.nuxt.com/scripts/marketing/clarity

**Comment by Barbapapazes** [comment]
fixed by https://github.com/Barbapapazes/nuxt-clarity-analytics/commit/31a4b54f412ec1f61d45e0ff1096b5660b111aa1
